### ISSUE TITLE
ONCE 1.5: invalid character '\t' in string literal

### ISSUE THREAD

**Issue by hussam-qasem** [oracle/vagrant-projects#435]
**Describe the issue**

I would like to upgrade the OCNE vagrant-project to v1.5. (And provide an option to deploy [MetalLB](https://docs.oracle.com/en/operating-systems/olcne/1.5/lb/metallb.html#metallb))

**Environment:**

- Host OS: macOS 12.3.1
- Kernel version: Darwin Kernel Version 21.4.0
- Vagrant version: 2.2.19
- Vagrant provider: VirtualBox: 6.1.34r150636
- Vagrant project: OCNE

**Additional information**

Validation fails for the Kubernetes module while running:
```
olcnectl module validate --environment-name ocne-env --name ocne-cluster
```
The following errors are printed in `/var/log/messages`:
```
May 12 12:29:40 master1 olcne-agent[10721]: time=12/05/22 12:29:40 level=error msg=An error occurred during ["/usr/libexec/syscheck" "get" "node-metadata" "{}"]: ["panic: runtime error: index out of range [0] with length 0" "" "goroutine 1 [running]:" "main.(*results).GetNodeMetaData(0xc000071200, {0xc0000711a0, 0x7ffc43475e09, 0xd})" "\t/root/rpmbuild/BUILD/go/src/linux-git.oraclecorp.com/OLCNE/olcne-lib/pkg/syscheck/main.go:605 +0x770" "main.main()" "\t/root/rpmbuild/BUILD/go/src/linux-git.oraclecorp.com/OLCNE/olcne-lib/pkg/syscheck/main.go:110 +0x1c5"]
May 12 12:29:40 master1 olcne-api-server[10636]: time=12/05/22 12:29:40 level=error msg=Could not unmarshal JSON result for resource node-metadata from 192.168.56.101:8090: invalid character '\t' in string literal
May 12 12:29:40 master1 olcne-api-server[10636]: time=12/05/22 12:29:40 level=error msg=The result string was: {"error":"panic: runtime error: index out of range [0] with length 0,,goroutine 1 [running]:,main.(*results).GetNodeMetaData(0xc000071200, {0xc0000711a0, 0x7ffc43475e09, 0xd}),#011/root/rpmbuild/BUILD/go/src/linux-git.oraclecorp.com/OLCNE/olcne-lib/pkg/syscheck/main.go:605 +0x770,main.main(),#011/root/rpmbuild/BUILD/go/src/linux-git.oraclecorp.com/OLCNE/olcne-lib/pkg/syscheck/main.go:110 +0x1c5", "user_action":[]}
May 12 12:31:49 master1 olcne-api-server[10636]: time=12/05/22 12:31:49 level=error msg=Could not unmarshal JSON result for resource node-metadata from 192.168.56.111:8090: invalid character '\t' in string literal
May 12 12:31:49 master1 olcne-api-server[10636]: time=12/05/22 12:31:49 level=error msg=The result string was: {"error":"panic: runtime error: index out of range [0] with length 0,,goroutine 1 [running]:,main.(*results).GetNodeMetaData(0xc000093200, {0xc0000931a0, 0x7fff6accde09, 0xd}),#011/root/rpmbuild/BUILD/go/src/linux-git.oraclecorp.com/OLCNE/olcne-lib/pkg/syscheck/main.go:605 +0x770,main.main(),#011/root/rpmbuild/BUILD/go/src/linux-git.oraclecorp.com/OLCNE/olcne-lib/pkg/syscheck/main.go:110 +0x1c5", "user_action":[]}
May 12 12:31:49 master1 olcne-api-server[10636]: time=12/05/22 12:31:49 level=error msg=Failed to fetch the current state of instance ocne-cluster of module kubernetes in ocne-env
```

@scoter-oracle any idea?

**Comment by hussam-qasem** [comment]
This is now resolved with [PR#436](https://github.com/oracle/vagrant-projects/pull/436). I'll submit a PR shortly.

**Comment by hussam-qasem** [comment]
Dear @scoter-oracle  / @rafabene  / @AmedeeBulle,

Would you be so kind to look into / approve my [PR #437](https://github.com/oracle/vagrant-projects/pull/437).

Kind regards,

Hussam

**Comment by scoter-oracle** [comment]
Merged approved, issue closed.
